<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>promise</title>
    </head>

    <body>
        Promise ---
        一个保存着某个未来才会结束的事件的容器、一个可以获取到异步操作的消息的对象...
        <ul>
            <li>
                Promise
                对象的状态不受外界影响，它有三种状态：pending(未完成)、fulfilled(已成功)、rejected(已失败)...
            </li>
            <li>只有异步操作的结果可以决定当前是哪一种状态...</li>
            <li>一旦状态改变，就不会再变，任何时候得到的都是一样结果...</li>
            <li>
                pending->fulfilled、pending->rejected，只要发生，状态就凝固，这是就称为
                resolved(已定型)...
            </li>
        </ul>
    </body>
    <script>
        const promise = new Promise(function(resolve, reject) {
            /*
            resolve & reject：
                resolve 函数：将状态从"未完成"变为"成功"，在异步操作成功时调用，并将异步操作的结果，作为参数传递出去...
                reject 函数：将状态从"未完成"变为"失败"，在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去...
            */
            console.log("promise"); // Promise 新建后就会立即执行...
            if (true) {
                resolve("resolve");
            } else {
                reject(error);
            }
        });
        // then 方法返回的是一个新的 Promise 实例...
        promise.then(
            function(value) {
                // 成功
                console.log(value);
            },
            function(error) {
                // 失败
            }
        );

        function timeout(ms) {
            return new Promise((resolve, reject) => {
                setTimeout(resolve, ms, "done");
            });
        }
        timeout(3000).then(value => {
            console.log(value);
        });

        function loadImgAsync(url) {
            return new Proimise((resolve, reject) => {
                const image = new Image();
                image.onload = function() {
                    resolve(image);
                };
                image.onerror = function(error) {
                    reject(error);
                };
                image.src = url;
            });
        }
        // Promise 实现 AJAX
        function getJson(url) {
            return new Promise(function(resolve, reject) {
                const handler = function() {
                    if (this.readyState !== 4) {
                        return;
                    }
                    if (this.status === 200 || this.status === 302) {
                        resolve(this.response);
                    } else {
                        reject(this.statusText);
                    }
                };
                const client = new XMLHttpRequest();
                client.open("GET", url);
                client.onreadystatechange = handler;
                client.responseType = "JSON";
                client.setRequestHeader("Accept", "application/json");
                client.send();
            });
        }
        /*getJson("https://www.baidu.com/#ie=UTF-8&wd=baidu").then(res => {
            console.log(res);
        }, error => {
            console.log(error);
        });*/
        // resolve/reject 函数参数除了正常值外，可以为另一个 Promise 实例...
        const p1 = new Promise((resolve, reject) => {
            setTimeout(reject(new Error("failure")), 3000);
        });
        const p2 = new Promise((resolve, reject) => {
            setTimeout(resolve(p1), 1000);
        });
        // 一般来说，不要在 then 方法里面定义 reject 状态的回调函数（即 then 的第二个参数），总是使用 catch 方法...
        p2.then(res => console.log(res))
            // catch 方法是 .then(null, rejection) 的别名，用于指定发生错误时的回调函数，也用=于接受 then 抛出的错误...
            .catch(error => console.log(error));
        // 调用 resolve/reject 并不会结束 Promise 的运行...
        new Promise((resolve, reject) => {
            resolve("start resolve...");
            // 一般来说，调用 resolve/reject 以后，Promise 的使命就完成了，后继操作应该放到 then 方法里面，所以最好 return resolve()/reject()...
            console.log("after rosolve...");
        }).then(res => {
            console.log(res);
        });
        /*
            finally 用于指定不管 Promise 对象最后状态如何，都会执行的操作...
            finally 方法的回调函数"不接受"任何参数，这意味着没有办法知道，前面的 Promise 状态到底是 fulfilled 还是 rejected...
                ---> finally 方法里面的操作，应该是与状态无关的，不依赖于 Promise 的执行结果...
        */
        Promise.resolve(2).then(
            v => {
                console.log(v);
            },
            () => {}
        );
        Promise.resolve(22).finally(v => {
            console.log(v); // undefined
        });
        /*
        Promise.all（具有 Iterator 接口的参数） --- 将多个 Promise 实例包装成为一个新的 Promise 实例...
            如果参数不是 Promise 实例的集合，就会先调用 Promise.resolve，将参数转换为 Promise 实例...
            ps = Promise.all([p1,p2,p3]);
                只有 p1、p2、p3 的状态都变成 fulfilled，ps 的状态才会变成 fulfilled，p1、p2、p3 的返回值组成一个数组，传递给 ps 的回调函数...
                p1、p2、p3 之中有一个被 rejected，ps 的状态就变成 rejected，此时第一个被 reject 的实例的返回值，会传递给p的回调函数...
        */
        const as1 = new Promise((resolve, reject) => {
            resolve("as1"); // resolve
        })
            .then(result => result)
            .catch(e => e);
        const as2 = new Promise((resolve, reject) => {
            // reject 但有自己的 catch 方法，不会触发 Promise.all 的 catch 方法...
            throw new Error("as2");
            // 如果没有 catch，就会触发 Promise.all 的 catch 方法...
        })
            .then(result => result)
            .catch(e => e); // reject -> resolve...
        const ass = Promise.all([as1, as2])
            .then(
                // ["as1", Error: as2]
                result => console.log(result)
            )
            .catch(e => console.log(e));
        /*
        Promise.race(具有 Iterator 接口的参数) --- 将多个 Promise 实例，包装成一个新的 Promise 实例...
            ps = Promise.all([p1,p2,p3]);
                只要 p1、p2、p3 之中有一个实例率先改变状态，ps 的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给 ps 的回调函数...
        */
        const bs1 = new Promise((resolve, reject) => {
            setTimeout(function() {
                resolve("bs1");
            }, 1000);
        })
            .then(result => result)
            .catch(e => e);
        const bs2 = new Promise((resolve, reject) => {
            setTimeout(function() {
                reject("bs2");
            }, 8000);
        })
            .then(result => result)
            .catch(e => e);
        const bss = Promise.race([bs1, bs2])
            .then(
                // bs1
                result => console.log(result)
            )
            .catch(e => console.log(e));
        /*
            Promise.resolve(参数) --- 将现有对象转为 Promise 对象...
            如果参数是 Promise 实例，那么 Promise.resolve 将不做任何修改、原封不动地返回这个实例...
        */
        Promise.resolve("lol");
        // 相当于...
        new Promise(resolve => resolve("lol"));
        // Promise.reject() --- 返回一个新的 Promise 实例，该实例的状态为 rejected...
        // Promise.reject("出错了");
        // 等同于
        // new Promise((resolve, reject) => reject("出错了"));
        /*
        Promise.try(f) --- 不知道或者不想区分，函数 f 是同步函数还是异步操作，但是想用 Promise 来处理它；
        这样就可以不管 f 是否包含异步操作，都用 then 方法指定下一步流程，用 catch 方法处理 f 抛出的错误...
        */
        const func = () => console.log("func");
        (async () => func())(); // func
        console.log("next"); // next
        // Promise.try(func); --- chrome 竟然不支持...
        console.log("at last...");
    </script>
</html>
